# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import predictor_pb2 as predictor__pb2


class LargeModelPredictorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_predictions = channel.unary_unary(
                '/LargeModelPredictor/get_predictions',
                request_serializer=predictor__pb2.Request.SerializeToString,
                response_deserializer=predictor__pb2.Response.FromString,
                )


class LargeModelPredictorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_predictions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LargeModelPredictorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_predictions': grpc.unary_unary_rpc_method_handler(
                    servicer.get_predictions,
                    request_deserializer=predictor__pb2.Request.FromString,
                    response_serializer=predictor__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'LargeModelPredictor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LargeModelPredictor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_predictions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/LargeModelPredictor/get_predictions',
            predictor__pb2.Request.SerializeToString,
            predictor__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
